#!/usr/bin/env python

from __future__ import annotations

from pathlib import Path

from fire import Fire
from config_formatter import ConfigFormatter


def format_cfg(filepath: str | Path):
    filepath = Path(filepath).expanduser().resolve()
    formatter = ConfigFormatter()
    formatted = formatter.prettify(filepath.read_text())
    print(formatted)


if __name__ == '__main__':
    Fire(format_cfg)
