#!/usr/bin/env python3

import json

import pyperclip
import typer


def main(input: str = '', output: str = 'proxy_tail.json'):
    if input:
        with open(input, "r") as f:
            xray_config = json.load(f)
    else:
        xray_config = json.loads(pyperclip.paste())

    for outbound in xray_config["outbounds"]:
        if outbound['tag'] == "proxy":
            proxy = outbound
            break

    if 'mux' in proxy:
        del proxy['mux']

    proxy_tail = {"outbounds": [proxy]}
    if output:
        with open(output, "w") as f:
            json.dump(proxy_tail, f, indent=4)
    else:
        pyperclip.copy(json.dumps(proxy_tail, indent=4))


if __name__ == '__main__':
    typer.run(main)
