config:
  raw.idmap: both 1000 1000
  environment.DISPLAY: :0
  environment.PULSE_SERVER: unix:/home/ubuntu/pulse-native
  nvidia.driver.capabilities: all
  nvidia.runtime: "true"
  user.user-data: |
    #cloud-config
    runcmd:
      - 'sed -i "s/; enable-shm = yes/enable-shm = no/g" /etc/pulse/client.conf'
    packages:
      - x11-apps
      - mesa-utils
      - pulseaudio
description: GUI LXD profile
devices:
  PASocket1:
    bind: container
    connect: unix:/run/user/1000/pulse/native
    listen: unix:/home/ubuntu/pulse-native
    security.gid: "1000"
    security.uid: "1000"
    uid: "1000"
    gid: "1000"
    mode: "0777"
    type: proxy
  X0:
    bind: container
    connect: unix:@/tmp/.X11-unix/X1
    listen: unix:@/tmp/.X11-unix/X0
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
  gpu:
    type: gpu
  cuda-11-3:
    source: /usr/local/cuda-11.3 # source path must be a regular file or directory, not a symlink
    path: /usr/local/cuda-11.3
    readonly: "true"
    type: disk
  # ssh:
  #   connect: tcp:0.0.0.0:22
  #   listen: tcp:0.0.0.0:2222
  #   type: proxy
  mnt-zw403:
    source: /home/zw403
    path: /mnt/zw403
    type: disk
name: x11
used_by: []
