[tool.ruff]
fix = true
select = [
	"F",
	"E",
	"W",
	"I",
	"UP",
	"N",
	"ASYNC",
	"FBT",
	"B",
	"A",
	"C4",
	"DTZ",
	"EM",
	"EXE",
	"PIE",
	"SLOT",
	"SIM",
	"INT",
	"PTH",
	"TD",
	"PD",
	"PL",
	"TRY",
	"FLY",
	"NPY",
	"RUF",
]
ignore = [
	"F401",
	"C408",
	"E402",
	"E501",
	"N803",
	"N806",
	"PTH123",
	"PLR0913",
	"PLR2004",
	"RUF001",
	"RUF002",
	"RUF003",
	"TRY300",
	"SIM905",
	"W191",
	"E111",
	"E114",
	"E117",
]

[tool.ruff.format]
line-ending = "lf"
quote-style = "single"
docstring-code-format = true
# 必须设为 false，否则会导致 isort 无法正常工作
skip-magic-trailing-comma = false

[tool.ruff.lint.isort]
length-sort = true
combine-as-imports = true
force-wrap-aliases = true
force-sort-within-sections = true
# required-imports = ["from __future__ import annotations"]
