version: "3"
services:
  web-check:
    # network_mode: host
    container_name: Web-Check
    ports:
      - 3000:3000
    image: lissy93/web-check
    restart: unless-stopped

    environment:
      - ALL_PROXY=http://host.docker.internal:8800
      - HTTP_PROXY=http://host.docker.internal:8800
      - HTTPS_PROXY=http://host.docker.internal:8800
      - all_proxy=http://host.docker.internal:8800
      - http_proxy=http://host.docker.internal:8800
      - https_proxy=http://host.docker.internal:8800
    extra_hosts:
      - "host.docker.internal:host-gateway"
