version: "3.3"
services:
  portainer-ce:
    container_name: portainer-cn
    restart: always
    stdin_open: true
    tty: true
    ports:
      #- 8000:8000 # http 端口，但是较新的版本已经不支持了
      - 9443:9443 # https 端口
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    image: 6053537/portainer-ce:2.19.4
