version: "3.3"
services:
  axolotl:
    container_name: x11
    image: xxxx
    stdin_open: true
    tty: true
    privileged: true
    ipc: host
    shm_size: 10g
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      - ~:/root
      - /tmp/.X11-unix/:/tmp/.X11-unix/
    # working_dir: ~
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
