name: $USER-cuda-$tag
services:
  cuda:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ROOT_PASSWD=$ROOT_PASSWD
    container_name: $USER-cuda-$tag
    image: bit0r/cuda:$tag
    stdin_open: true
    tty: true
    restart: unless-stopped
    privileged: true
    ipc: host
    shm_size: 10g
    ulimits:
      memlock: -1
      stack: 67108864
    init: true
    volumes:
      # - /tmp/.X11-unix/:/tmp/.X11-unix/:ro
      - ~:$HOME
      - /data/:/mnt/data/
      - /usr/local/bin/:/mnt/usr/local/bin/:ro
      - /etc/fish/:/etc/fish/:ro
      - ./setup.fish:/mnt/setup.fish:ro
    user: $USER
    working_dir: $HOME
    command: /mnt/setup.fish
    ports:
      - 2$UID:22
      - 5$UID:5901
    environment:
      - DISPLAY
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
