version: "3.8"
services:
  lobe-chat:
    image: lobehub/lobe-chat
    container_name: lobe-chat
    restart: always
    ports:
      - 3210:3210
    environment:
      # Implicitly environment variables
      - OPENAI_API_KEY
      - OPENAI_PROXY_URL
      - ACCESS_CODE
