pages:
  - name: News
    columns:
      - size: full
        widgets:
          - type: hacker-news

          - type: rss
            style: horizontal-cards
            # limit: 10
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://quarto.org/docs/blog/index.xml
              - url: https://feeds.feedburner.com/UbuntuhandbookNewsTutorialsHowtosForUbuntuLinux

          - type: rss
            style: horizontal-cards
            limit: 500
            title: Github Daily Trending
            collapse-after: 3
            cache: 3h

            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml
                title: Github Daily Trending All

          - type: rss
            style: horizontal-cards
            limit: 500
            title: Github Weekly Trending
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/weekly/all.xml
                title: Github Weekly Trending All

          - type: rss
            style: horizontal-cards
            limit: 500
            title: Github Monthly Trending
            collapse-after: 3
            cache: 3h
            feeds:
              - url: https://mshibanami.github.io/GitHubTrendingRSS/monthly/all.xml
                title: Github Monthly Trending All

      - size: small
        widgets:
          - type: stocks
            stocks:
              - symbol: NVDA
                name: NVIDIA
              - symbol: MSFT
                name: Microsoft
              - symbol: AAPL
                name: Apple
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: BTC-USD
                name: Bitcoin

  - name: Videos
    columns:
      - size: full
        widgets:
          - type: videos
            style: grid-cards
            channels:
              - UCMUnInmOkrWN4gof9KlhNmQ # 老高與小茉 Mr. Gao & Ms. Mo
              - UCgo_-fjJxnLwwwq5dSY72rg # 自说自话的总裁
              - UCTu_hTaVf3DJMpMIyOAq2Ew # 文昭思绪飞扬
              - UC2lbb8vjQR64C6gHqD0_4OA # 你可敢信

      - size: small
        widgets:
          - type: twitch-top-games
            collapse-after: 100

  - name: Sites
    columns:
      - size: full
        widgets:
          - type: monitor
            style: dynamic-columns-experimental
            cache: 1m
            sites:
              - title: LobeChat
                url: http://localhost:3210
                icon: http://localhost:3210/favicon.ico

              - title: portainer-cn
                url: https://localhost:9443
                icon: https://localhost:9443/1197a68684b9ff08165a.ico

              - title: paperless-ngx
                url: http://localhost:8010
                icon: http://localhost:8010/favicon.ico

              - title: LXD UI
                url: https://localhost:8443
                icon: https://localhost:8443/ui/assets/img/favicon-32x32.png

              - title: Aria2 RPC
                url: https://localhost:6800/jsonrpc
                icon: https://aria2.github.io/favicon.png

              - title: WebRTC
                url: http://zw403-1080ti:8888
                icon: http://zw403-1080ti:8888/static/img/favicon-32x32.png

              - title: doggo
                url: http://localhost:7788

  - name: Weather
    columns:
      - size: full
        widgets:
          - type: iframe
            source: https://tianqi.moji.com/weather/china/hunan/yuhu-district
            height: 700

server:
  port: 2345
  assets-path: /opt/glance/assets

theme:
  light: true
  background-color: 28 40 77
  primary-color: 155 100 20
  negative-color: 0 100 60
  contrast-multiplier: 1.1
  text-saturation-multiplier: 0.5
