auto_save: true
display_label_popup: true
store_data: false
keep_prev: false
keep_prev_scale: false
keep_prev_brightness: false
keep_prev_contrast: false
logger_level: info

flags: null
label_flags: null
labels: null
file_search: null
sort_labels: true
validate_label: null

default_shape_color: [0, 255, 0]
shape_color: auto # null, 'auto', 'manual'
shift_auto_shape_color: 0
label_colors: null

shape:
  # drawing
  line_color: [0, 255, 0, 128]
  fill_color: [0, 255, 0, 0] # transparent
  vertex_fill_color: [0, 255, 0, 255]
  # selecting / hovering
  select_line_color: [255, 255, 255, 255]
  select_fill_color: [0, 255, 0, 155]
  hvertex_fill_color: [255, 255, 255, 255]
  point_size: 8

# main
flag_dock:
  show: true
  closable: true
  movable: true
  floatable: true
label_dock:
  show: true
  closable: true
  movable: true
  floatable: true
shape_dock:
  show: true
  closable: true
  movable: true
  floatable: true
file_dock:
  show: true
  closable: true
  movable: true
  floatable: true

# label_dialog
show_label_text_field: true
label_completion: startswith
fit_to_content:
  column: true
  row: false

# canvas
epsilon: 10.0
canvas:
  # None: do nothing
  # close: close polygon
  double_click: close
  # The max number of edits we can undo
  num_backups: 10
  # show crosshair
  crosshair:
    polygon: false
    rectangle: true
    circle: false
    line: false
    point: false
    linestrip: false
